package mappers;

public enum MirroringType {
    VERTICAL_MIRRORING,
    HORIZONTAL_MIRRORING,
    FOURSCREEN_MIRRORING,
    SINGLESCREEN_MIRRORING,
    SINGLESCREEN_MIRRORING2,
    SINGLESCREEN_MIRRORING3,
    SINGLESCREEN_MIRRORING4,
    CHRROM_MIRRORING;
}